# Generated by Django 4.2.10 on 2024-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authors', models.CharField(max_length=100)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('small_cover_link', models.URLField(blank=True, null=True)),
                ('cover_link', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
