# Generated by Django 4.2.10 on 2024-03-31 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_count', models.IntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('not_started', 'Not Started'),
                            ('in_progress', 'In Progress'),
                            ('finished', 'Finished')
                        ],
                        default='not_started',
                        max_length=20
                    )
                 ),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
